### ISSUE TITLE
Make "open", "create" have same format as "write"

### ISSUE THREAD

**Issue by Alaya-in-Matrix** [AD7six/vim-activity-log#6]
Why would the format of `open` and `create` is different from that of `write`? 

would it be better to replace 

```
let l:message = value . ' ' . key  . ' ' . l:file` 
```

with 

```
let l:message = value . ';' . key  . ';' . l:file
```

?

**Comment by AD7six** [comment]
Looks like a typo that nobody noticed, the code for this plugin could do with consolidating a bit too.

**Comment by Alaya-in-Matrix** [comment]
Do you have any plan to have it modified, or should I make a pull request?

**Comment by AD7six** [comment]
Sorry for the egregiously late reply, I'll be archiving this project as I don't use or maintain it these days :).
