### ISSUE TITLE
file permission with root

### ISSUE THREAD

**Issue by liuyang1** [AD7six/vim-activity-log#8]
If open some file with `sudo` first, it will create `$HOME/[year]/[month]/[day].log` 644 permission with `root` user.

so if I run vi again with normal user and try to write that file, it fail to write log file, as that file belong to `root`.

Do we have any solution on this problem?

I think this issue is related to umask of root.

**Comment by AD7six** [comment]
I do not have a solution to this other than `chown -R me:me ~/activity` to fix these circumstances. 

Sorry for the egregiously late reply, I'll be archiving this project as I don't use or maintain it these days :).
